### ISSUE TITLE
Notes for processes in Linux

### ISSUE THREAD

**Issue by apoorv-on-git** [virtual-tech-school/virtual-tech-notes#24]
Notes for Processes in Linux are still missing - https://github.com/virtual-tech-school/virtual-tech-notes/tree/main/linux-masterclass/05-processes

**Comment by hindu-muppala** [comment]
@apoorv-on-git , I am interested to add notes ,Can you assign this issue to me?

**Comment by apoorv-on-git** [comment]
@hindu-muppala Sure thing. This issue is yours!

**Comment by apoorv-on-git** [comment]
This issue is now closed.
