### ISSUE TITLE
Notes for Partitions in Linux

### ISSUE THREAD

**Issue by apoorv-on-git** [virtual-tech-school/virtual-tech-notes#25]
Notes for Partitions in Linux are still missing - https://github.com/virtual-tech-school/virtual-tech-notes/tree/main/linux-masterclass/05-processes

**Comment by uncleSlayer** [comment]
I would like to write this one.

**Comment by apoorv-on-git** [comment]
Thanks, @uncleSlayer! I've assigned it to you.

**Comment by hindu-muppala** [comment]
@uncleSlayer ,if you not working ,Can I complete this issue?

**Comment by hindu-muppala** [comment]
@apoorv-on-git ,Can I complete this issue?

**Comment by apoorv-on-git** [comment]
Sure @hindu-muppala, feel free to take this up.

**Comment by apoorv-on-git** [comment]
Marking this issue as closed.
