### ISSUE TITLE
Notes for Resource Utilisation in Linux

### ISSUE THREAD

**Issue by apoorv-on-git** [virtual-tech-school/virtual-tech-notes#26]
Notes for Resource Utilisation are still missing - https://github.com/virtual-tech-school/virtual-tech-notes/tree/main/linux-masterclass/05-processes

**Comment by hindu-muppala** [comment]
@apoorv-on-git ,I want to add notes for Resource Utilisation. Can you assign this issue to me?

**Comment by apoorv-on-git** [comment]
I've assigned it to you. Thank you.

**Comment by apoorv-on-git** [comment]
This issue is now marked as closed.
