### ISSUE TITLE
Notes for HTML Inline & Block Elements

### ISSUE THREAD

**Issue by apoorv-on-git** [virtual-tech-school/virtual-tech-notes#30]
Notes for HTML Inline & Block Elements are missing - https://github.com/virtual-tech-school/virtual-tech-notes/tree/main/frontend-101/02-block-and-inline

**Comment by adityadafe** [comment]
Can i take this issue ?

**Comment by apoorv-on-git** [comment]
Thanks, @KaKashi1210. I've assigned this to you.

**Comment by Vamsieth** [comment]
made properly structured notes, can I go ahead?

**Comment by apoorv-on-git** [comment]
@Vamsieth if you have made handwritten notes - sure go ahead. For the markdown notes, let's wait for @KaKashi1210's commit as it is assigned to his currently.

There will be more videos coming out eventually. You can take up notes for them or improve the existing ones.

**Comment by Vamsieth** [comment]
I was also talking about markdown notes, I started doing it since I commented. It's almost finished.. 

how about I'll make a pr and you choose the best one. It's up to you bro :) 

Your tutorials are insightful, love your explanation bro. 
wanted to thank you personally.

**Comment by apoorv-on-git** [comment]
Thanks @Vamsieth for your kind words.

@KaKashi1210 Can you take a look at the notes @Vamsieth has provided? If you can make any improvements, that would be better, and if you've created the markdown already, then you might need to take a pull on the base repo before adding your notes as there would now be merge conflicts.

**Comment by adityadafe** [comment]
@apoorv-on-git sure no problem 😊

**Comment by apoorv-on-git** [comment]
Marking this issue as closed.
