### ISSUE TITLE
Notes for CSS grids

### ISSUE THREAD

**Issue by Vamsieth** [virtual-tech-school/virtual-tech-notes#44]

**Comment by VenkataBhaskarr** [comment]
@Vamsieth you can go ahead and contribute the notes for CSS grids.

**Comment by Vamsieth** [comment]
yeah, I did a PR pls checkout

**Comment by apoorv-on-git** [comment]
I've approved it. Closing this issue, thank you @Vamsieth and @VenkataBhaskarr.
