### ISSUE TITLE
Notes for Bootstrap

### ISSUE THREAD

**Issue by apoorv-on-git** [virtual-tech-school/virtual-tech-notes#52]
Notes for Bootstrap as still missing - https://github.com/virtual-tech-school/virtual-tech-notes/blob/main/frontend-101/05-bootstrap/README.md

**Comment by Princekanaugia** [comment]
Hello Apoorv
i had watched the Bootstrap video and understood it well. i would like to contribute in making this note. so, can you assign it to me.

**Comment by apoorv-on-git** [comment]
Thanks, @Princekanaugia for taking this up. I'm assigning it to you.

**Comment by apoorv-on-git** [comment]
Closing this issue.
