### ISSUE TITLE
Adding contributors section in redme.md if necessary

### ISSUE THREAD

**Issue by hindu-muppala** [virtual-tech-school/virtual-tech-notes#53]
How to add : 
```
<a href="https://github.com/virtual-tech-school/virtual-tech-notes/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=virtual-tech-school/virtual-tech-notes" />
</a>


```
copy and path the above markup in redme.md

**Comment by apoorv-on-git** [comment]
Thanks for the suggestion @hindu-muppala, feel free to do that and raise a PR

**Comment by shubhxg** [comment]
I think he is not responding, you can assign me only if you want @apoorv-on-git :)

**Comment by apoorv-on-git** [comment]
Thanks for completing this @hindu-muppala. Closing it

**Comment by shubhxg** [comment]
Ok great its merged 👍🏼
